pr:
  branches:
    include:
      - '*'

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: jfrog-config

jobs:
  - job: FrogbotScanPullRequest
    displayName: Frogbot Scan Pull Request
    steps:
      - checkout: self

      - script: |
          curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v3/[RELEASE]/getFrogbot.sh" | sh
          ./frogbot scan-pull-request
        displayName: Run Frogbot PR scan
        env:
          JF_URL: $(JF_URL)
          JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
          JF_GIT_TOKEN: $(System.AccessToken)
          JF_PROJECT_KEY: $(JF_PROJECT_KEY)
          JF_GIT_PROVIDER: azureRepos
          JF_GIT_API_ENDPOINT: $(System.CollectionUri)
          JF_GIT_OWNER: $(System.TeamProject)
          JF_GIT_PROJECT: $(System.TeamProject)
          JF_GIT_REPO: $(Build.Repository.Name)
          JF_GIT_BASE_BRANCH: $(System.PullRequest.TargetBranch)
          JF_GIT_PULL_REQUEST_ID: $(System.PullRequest.PullRequestId)
