schedules:
  - cron: '0 0 * * *'
    displayName: Daily midnight scan
    branches:
      include:
        - main

pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: jfrog-config
  - name: JF_GIT_OWNER
    value: markwme

jobs:
  - job: FrogbotScanRepository
    displayName: Frogbot Scan Repository
    steps:
      - task: CmdLine@2
        displayName: Download and Run Frogbot
        env:
          JF_URL: $(JF_URL)
          JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
          JF_GIT_TOKEN: $(JF_GIT_TOKEN)
          JF_GIT_OWNER: $(JF_GIT_OWNER)
        inputs:
          script: |
            curl -fL "https://releases.jfrog.io/artifactory/frogbot/v3/$(FROGBOT_VERSION)/getFrogbot.sh" | sh
            ./frogbot scan-repository
