name: Setup JFrog command line
runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v4
      with:
        version: latest
        oidc-provider-name: ${{ env.JF_OIDC_PROVIDER }}
        oidc-audience: ${{ env.JF_URL }}
